export const ECStatus = {
  ERROR: 'error',
  SUCCESS: 'success',
  DEFAULT: ''
};

export const ECEvent = {
  TASK_CREATED: 'ecTaskCreated',
  TASK_ORDER_PLACED: 'ecTaskOrderPlaced',
  TASK_NOT_PROCESSED: 'ecTaskNotProcessed',
  TASK_PROGRESS: 'ecTaskProgress',
  TASK_COMPLETED: 'ecTaskCompleted'
};

export const ECOrderTaskStatus = {
  0: 'SUCCESS',
  1: 'SYSTEM_ERROR',
  2: 'KEY_ERROR',
  3: 'SYNTAX_WARNING',
  4: 'BASE_EXCEPTION',
  5: 'PAYLOAD_NOT_DEFINED',
  6: 'PAYLOAD_CHECKSUM_ERROR',
  7: 'INPUT_CHECKSUM_ERROR'
};

export const ECOrderTaskStatusCode = {
  SUCCESS: 'SUCCESS',
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  KEY_ERROR: 'KEY_ERROR',
  SYNTAX_WARNING: 'SYNTAX_WARNING',
  BASE_EXCEPTION: 'BASE_EXCEPTION',
  PAYLOAD_NOT_DEFINED: 'PAYLOAD_NOT_DEFINED',
  PAYLOAD_CHECKSUM_ERROR: 'PAYLOAD_CHECKSUM_ERROR',
  INPUT_CHECKSUM_ERROR: 'INPUT_CHECKSUM_ERROR'
};

export const ECNetwork = {
  BLOXBERG_TESTNET: 'Bloxberg TESTNET',
  BLOXBERG_MAINNET: 'Bloxberg MAINNET',
  POLYGON_TESTNET: 'Polygon TESTNET',
  POLYGON_MAINNET: 'Polygon MAINNET'
};

export const ECRunner = {
  PYNITHY_RUNNER_TESTNET: 'etny-pynithy-testnet',
  NODENITHY_RUNNER_TESTNET: 'etny-nodenithy-testnet',
  PYNITHY_RUNNER: 'etny-pynithy',
  NODENITHY_RUNNER: 'etny-nodenithy'
};

export const ECAddress = {
  BLOXBERG_TESTNET_ADDRESS: '0x02882F03097fE8cD31afbdFbB5D72a498B41112c',
  BLOXBERG_MAINNET_ADDRESS: '0x549A6E06BB2084100148D50F51CF77a3436C3Ae7',
  POLYGON_TESTNET_ADDRESS: '0xB2bAEbB29544D513062571dD28b8f188eC996Cc3',
  POLYGON_MAINNET_ADDRESS: ''
};

export const ZERO_CHECKSUM = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';

export const ECError = {
  PARSE_ERROR: 'EtnyParseError',
  IPFS_DOWNLOAD_ERROR: 'ECIPFSDownloadError'
};
